services:
  run-hardhat-node:
    build: .
    container_name: run-hardhat-node
    ports:
      - "8545:8545"
    volumes:
      - shared-data:/app
    command: [ "bash", "-c", "./docker/run_test_node.sh > /dev/null 2>&1" ]

  test-runner:
    build: .
    network_mode: "service:run-hardhat-node"
    container_name: test-runner
    depends_on:
      run-hardhat-node:
        condition: service_started
    volumes:
      - shared-data:/app
    command: [ "bash", "-c", "./docker/run_tests.sh" ]

volumes:
  shared-data:
